exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - update-directory-index.sh

groups:
  guidance_on_digital_services:
    name: Guidance on digital services
    bio: We create and maintain guidance on creating great digital government services.
    links:
      - name: Service Manual
        url: https://www.gov.uk/service-manual
        description: Helping government teams create and run great digital services that meet the Digital Service Standard.
      - name: Government Design Principles
        url: https://www.gov.uk/design-principles
        description: The UK government's design principles and examples of how they've been used.
      - name: Service Toolkit
        url: https://www.gov.uk/service-toolkit
        description: All you need to design, build and run services that meet government standards.
  govuk_templates_and_styles:
    name: GOV.UK templates and styles
    bio: |
      We offer templates and styles to help government departments create services that fit the
      GOV.UK look and feel.
    repos:
      - govuk-frontend
  transitioning_to_govuk:
    name: Transitioning to GOV.UK
    bio: |
      We built a set of tools to support the transition from DirectGov, BusinessLink and a host
      of other websites onto GOV.UK. You can read an overview of that in
      <a href='https://gds.blog.gov.uk/2012/10/11/no-link-left-behind/'>No Link Left Behind</a> and
      <a href='https://gds.blog.gov.uk/2012/12/10/testing-the-redirections/'>Testing The Redirections</a>.
    repos:
      - bouncer
      - transition
      - side-by-side-browser
  performance_platform:
    name: Performance Platform
    bio: |
      The <a href='https://www.gov.uk/performance'>Performance Platform</a>
      team creates dashboards to show the performance of
      government over time. We occasionally post on the
      <a href='https://gdsdata.blog.gov.uk/'>Data at GDS</a> blog.
    repos:
      - backdrop
      - cheapseats
      - spotlight
      - stagecraft
  libraries_and_utilities:
    name: Libraries and utilities
    repos:
      - govuk-browser-extension
      - govuk-saas-config
      - magna-charta
      - sbv-to-ttaf
      - sidekiq-monitoring
  office_tools:
    name: Tools for the office
    bio: We have a lot of code that shows up on displays around our office or posts in our Slack channels.
    repos:
      - fourth-wall
      - gds-hubot
      - govuk-display-screen
      - govuk-dependencies
      - govuk-deploy-lag-badger
      - seal
      - showtime
